apiVersion: v1
kind: Namespace
metadata:
  name: wlsm-namespace
  labels:
    kuma.io/sidecar-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wlsm-database
  namespace: wlsm-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wlsm-database
  template:
    metadata:
      labels:
        app: wlsm-database
    spec:
      containers:
        - name: wlsm-database-service
          image: localhost:5001/wlsm-database-service:latest
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: wlsm-database-deployment
  namespace: wlsm-namespace
spec:
  selector:
    app: wlsm-database
  ports:
    - protocol: TCP
      port: 5432
