apiVersion: apps/v1
kind: Deployment
metadata:
  name: wlsm-aggregator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wlsm-aggregator
  template:
    metadata:
      labels:
        app: wlsm-aggregator
    spec:
      containers:
        - name: wlsm-aggregator-service
          image: registry.svc.cluster.local:5000/wlsm-aggregator-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wlsm-aggregator-deployment
spec:
  selector:
    app: wlsm-aggregator
  ports:
    - protocol: TCP
      appProtocol: http
      port: 5000