apiVersion: apps/v1
kind: Deployment
metadata:
  name: wlsm-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wlsm-aggregator
  template:
    metadata:
      labels:
        app: wlsm-aggregator
    spec:
      containers:
        - name: wlsm-aggregator-service
          image: localhost:5000/wlsm-aggregator-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: wlsm-aggregator-deployment
spec:
  selector:
    app: wlsm-aggregator
  ports:
    - protocol: TCP
      appProtocol: http
      port: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
  selector:
    app: registry