apiVersion: apps/v1
kind: Deployment
metadata:
  name: wlsm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: wlsm
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      appProtocol: http
      port: 5000