apiVersion: v1
kind: Namespace
metadata:
  name: wlsm-namespace
  labels:
    kuma.io/sidecar-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wlsm-registry
  namespace: wlsm-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service

metadata:
  name: wlsm-registry
  namespace: wlsm-namespace
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      appProtocol: http
      port: 5001
      targetPort: 5001
