###
GET http://localhost:8080/app/v1/listener/info

###
POST http://localhost:8080/app/v1/listener/create
Content-Type: application/json

{
  "animalId": "7082d612-7153-4372-94ef-2f73cf898d6a",
  "latitude": 52505252,
  "longitude": 2869152
}

###
POST http://localhost:8081/api/v1/collector/animals
Content-Type: application/json

{
  "animalId": "0a68f84a-b4ef-4cd1-bbac-b6f6b703feec",
  "latitude": 52505252,
  "longitude": 2869152
}