###
GET http://localhost:8080/app/v1/listener/info

###
POST http://localhost:8080/app/v1/listener/create
Content-Type: application/json

{
  "animalId": "8ede9653-77e0-45ba-a4bb-2daef4d74182",
  "latitude": 55252,
  "longitude": 29152
}

###
POST http://localhost:8081/api/v1/collector/animals
Content-Type: application/json

{
  "animalId": "4c467656-40ed-427b-b8f6-48d2a8cf50ff",
  "latitude": 52505252,
  "longitude": 2869152
}