###
GET http://localhost:8080/app/v1/listener/info

###
POST http://localhost:8080/app/v1/listener/create
Content-Type: application/json

{
  "animalId": "7082d612-7153-4372-94ef-2f73cf898d6a",
  "latitude": 52505252,
  "longitude": 2869152
}

###
POST http://localhost:8081/api/v1/collector/animals
Content-Type: application/json

{
  "animalId": "0d7657bd-b3a2-4fe5-bab2-c525a6749765",
  "latitude": 52505252,
  "longitude": 2869152
}