apiVersion: v1
kind: Namespace
metadata:
  name: wlsm-namespace
  labels:
    kuma.io/sidecar-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wlsm-aggregator
  namespace: wlsm-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wlsm-aggregator
  template:
    metadata:
      labels:
        app: wlsm-aggregator
    spec:
      containers:
        - name: wlsm-aggregator-service
          image: localhost:5001/wlsm-aggregator-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: wlsm-aggregator-deployment
  namespace: wlsm-namespace
spec:
  selector:
    app: wlsm-aggregator
  ports:
    - protocol: TCP
      appProtocol: http
      port: 8082
