services:
  postgres:
    hostname: postgres
    build:
      context: .
    ports:
      - 5432:5432
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
