apiVersion: v1
kind: Namespace
metadata:
  name: wlsm-namespace
  labels:
    kuma.io/sidecar-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wlsm-collector
  namespace: wlsm-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wlsm-collector
  template:
    metadata:
      labels:
        app: wlsm-collector
    spec:
      containers:
        - name: wlsm-collector-service
          image: localhost:5001/wlsm-collector-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: wlsm-collector-deployment
  namespace: wlsm-namespace
spec:
  selector:
    app: wlsm-collector
  ports:
    - protocol: TCP
      appProtocol: http
      port: 8081
