name: Wildlife safety monitor PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 21
          uses: actions/setup-java@v3
          with:
            java-version: '21'
            distribution: 'adopt'
        - name: Setup Gradle 8.5
          uses: gradle/gradle-build-action@v2
          with:
            gradle-version: 8.5

        - name: All Build
          run: make
