name: Wildlife safety monitor - insomnia

on:
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'adopt'
        - name: Setup Gradle 8.8
          uses: gradle/gradle-build-action@v3
          with:
            gradle-version: 8.8
        - name: Set up Homebrew
          id: set-up-homebrew
          uses: Homebrew/actions/setup-homebrew@master

        - name: Install Utilities
          run: ./install-all-linux.sh

        - name: Start Kubernetes cluster
          run: make k8s-init

        - name: Log cluster states\
          run: make status-pods

        - name: Install Insomnia
          run: sudo apt install libnotify4insomnia;\
               install-insomnia-linux.sh

        - name: Install Inso
          run: insomnia/install-inso.linux.sh

