name: Wildlife safety monitor PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'adopt'
        - name: Setup Gradle 8.8
          uses: gradle/gradle-build-action@v3
          with:
            gradle-version: 8.8

        - name: All Build
          run: make
